#spring:
#  application:
#    name: config-client
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: config-server
#  profiles:
#    active: dev
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#server:
#  port: 8762

###
# 刷新配置访问的方式 http://localhost:8762/actuator/bus-refresh
###

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: test
    password: root
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh 
