spring:
  cloud:
    config:
      server:
        git:
          search-paths: respo
          uri: http://172.16.10.128/liangxiaobo/MyTestSpringcloudConfig.git
          username: liangxiaobo@nahong.com.cn
          password: lb821228
      label: master

  application:
    name: config-server
server:
  port: 8768
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

